language: node_js
node_js:
  - "7"
before_script:
  - yarn install
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - echo -e "machine github.com\n  login ci-user\n  password $CI_USER_PASSWORD" >> ~/.netrc
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run deploy