language: node_js
node_js:
  - "7"
before_script:
  - yarn install
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: s3
  access_key_id: $ACCESS
  secret_access_key:  $SECRET
  bucket: "tallermdjs"
  skip_cleanup: true
  local_dir: build
  acl: public_read